[metadata]
name = sal_cs
version = 0.1.0-dev
author = D.G. MacCarthy
author_email = sc8pr.py@gmail.com
description = Coding exercises/resources for Computing Science students
long_description = file: README.md
long_description_content_type = text/markdown
keywords = educational
license = GPLv3
classifiers =
	Development Status :: 2 - Pre-Alpha
	Intended Audience :: Education
	License :: OSI Approved :: GNU General Public License v3 (GPLv3)
	Programming Language :: Python :: 3
	Topic :: Education

[options]
zip_safe = False
include_package_data = True
packages = find:
